CREATE  DATABASE inlock_games;
GO

USE inlock_games;
GO

CREATE TABLE Studio
(
	Id INT PRIMARY KEY IDENTITY,
	[Name] VARCHAR(100) NOT NULL
);
GO

CREATE TABLE Game
(
	Id INT PRIMARY KEY IDENTITY,
	IdStudio INT FOREIGN KEY REFERENCES Studio(Id),
	[Name] VARCHAR(100) NOT NULL, 
	[Description] VARCHAR(100) NOT NULL,
	ReleaseDate DATE NOT NULL, 
	Price SMALLMONEY NOT NULL
);
GO

CREATE TABLE UserType
(
	Id INT PRIMARY KEY IDENTITY,
	TypeName VARCHAR(100) NOT NULL
);
GO

CREATE TABLE [User]
(
	Id INT PRIMARY KEY IDENTITY,
	IdUserType INT FOREIGN KEY REFERENCES UserType(Id),
	Email VARCHAR(100) NOT NULL UNIQUE,
	[Password] VARCHAR (100) NOT NULL
);
GO
